// Inhoud per land: feitjes (NL), grappige woordjes [woord, taal, betekenis] en
// foto-onderwerpen [weergavenaam, wikipedia-artikel, taalwiki]. De foto-URL's
// worden door bouw-inhoud.mjs opgezocht via de Wikipedia REST-API en geverifieerd.
export default {
NL:{
 feiten:[
  "In Nederland zijn meer fietsen dan mensen — zo'n 23 miljoen!",
  "Ongeveer een kwart van Nederland ligt onder de zeespiegel; Schiphol ligt ruim 4 meter onder zeeniveau.",
  "Wortels zijn oranje gemaakt door Nederlandse kwekers, als eerbetoon aan Oranje.",
  "Het Koninklijk Paleis op de Dam staat op 13.659 houten palen.",
  "Tulpen komen oorspronkelijk niet uit Nederland, maar uit Turkije.",
  "De Vaalserberg is met 322 meter het hoogste puntje van Nederland.",
  "In Kinderdijk staan 19 oude windmolens op een rij — werelderfgoed!",
  "De stroopwafel is ruim 200 jaar geleden bedacht in Gouda.",
  "Nederland is de op één na grootste voedselexporteur ter wereld — na de enorme VS.",
  "De Elfstedentocht is een schaatstocht van bijna 200 kilometer door Friesland."],
 woorden:[["flierefluiter","Nederlands","iemand die lekker niks loopt te doen"],
  ["kwebbelkont","Nederlands","iemand die niet kan stoppen met kletsen"],
  ["apekool","Nederlands","grote onzin"],
  ["uitwaaien","Nederlands","lekker in de wind lopen om je hoofd leeg te maken"],
  ["snotneus","Nederlands","brutaal jong kind"],
  ["hatseflats","Nederlands","zomaar ineens, hup!"]],
 fotos:[["Rijksmuseum","Rijksmuseum Amsterdam","nl"],["Molens van Kinderdijk","Kinderdijk","nl"],["Domtoren van Utrecht","Domtoren","nl"],["Keukenhof","Keukenhof","nl"],["Paleis op de Dam","Paleis op de Dam","nl"],["Erasmusbrug","Erasmusbrug","nl"],["Afsluitdijk","Afsluitdijk","nl"],["Euromast","Euromast","nl"],["Oosterscheldekering","Oosterscheldekering","nl"],["Magere Brug","Magere Brug","nl"]]},
BE:{
 feiten:[
  "Friet is uitgevonden in België — nergens eten ze meer frietjes per persoon!",
  "België maakt meer dan 220.000 ton chocolade per jaar.",
  "Het smurfenland: de Smurfen zijn bedacht door de Belg Peyo.",
  "Kuifje en Lucky Luke komen ook uit België — het stripland van Europa.",
  "In België bestaan meer dan 1000 soorten bier.",
  "Manneken Pis in Brussel heeft een kledingkast met meer dan 1000 pakjes.",
  "Het Atomium is een ijzerkristal, 165 miljard keer vergroot.",
  "België heeft drie officiële talen: Nederlands, Frans en Duits.",
  "De saxofoon is uitgevonden door de Belg Adolphe Sax.",
  "Brussel wordt de hoofdstad van Europa genoemd: daar vergadert de EU."],
 woorden:[["curieuzeneuzemosterdpot","Vlaams","een héél nieuwsgierig iemand"],
  ["dikkenek","Vlaams","opschepper"],
  ["amai","Vlaams","wauw, tjonge!"],
  ["frietkot","Vlaams","friettentje"],
  ["zwanzen","Vlaams","grapjes maken"],
  ["kabas","Vlaams","boodschappentas"]],
 fotos:[["Atomium","Atomium","nl"],["Manneken Pis","Manneken Pis","nl"],["Grote Markt van Brussel","Grote Markt (Brussel)","nl"],["Belfort van Brugge","Belfort (Brugge)","nl"],["Gravensteen","Gravensteen (Gent)","nl"],["Koninklijk Paleis van Brussel","Koninklijk Paleis (Brussel)","nl"],["Basiliek van Koekelberg","Basiliek van Koekelberg","nl"],["Boekentoren","Boekentoren","nl"]]},
LU:{
 feiten:[
  "In Luxemburg zijn alle bussen en treinen gratis!",
  "Luxemburg is het enige groothertogdom ter wereld.",
  "Bijna de helft van de mensen die er werken, woont in een buurland.",
  "Luxemburg-Stad staat op rotsen vol oude gangen: de kazematten.",
  "Luxemburg is een van de rijkste landen ter wereld.",
  "Het land is kleiner dan de provincie Gelderland.",
  "Luxemburgers spreken drie talen door elkaar: Luxemburgs, Frans en Duits."],
 woorden:[["Gromperekichelcher","Luxemburgs","aardappelkoekjes — probeer maar eens te zeggen!"],
  ["Fuurz","Luxemburgs","scheet"],
  ["Päiperlek","Luxemburgs","vlinder"],
  ["Kaz","Luxemburgs","kat"]],
 fotos:[["Groothertogelijk Paleis","Groothertogelijk paleis (Luxemburg)","nl"],["Kasteel van Vianden","Kasteel van Vianden","nl"],["Adolphebrug","Adolphe Bridge","en"],["Kazematten van de Bock","Bock (Luxembourg)","en"],["Gëlle Fra","Gëlle Fra","en"]]},
DE:{
 feiten:[
  "Het sprookjeskasteel Neuschwanstein was het voorbeeld voor het Disney-kasteel.",
  "Duitsland heeft meer dan 1500 soorten worst en 300 soorten brood.",
  "Gummibeertjes zijn uitgevonden in Duitsland, door Hans Riegel van Haribo.",
  "Op delen van de Duitse Autobahn is geen maximumsnelheid.",
  "De boekdrukkunst is rond 1450 uitgevonden door de Duitser Gutenberg.",
  "Het Oktoberfest in München is het grootste volksfeest ter wereld.",
  "De kerstboom-traditie komt oorspronkelijk uit Duitsland.",
  "Duitsland telt meer dan 25.000 kastelen en burchten.",
  "De stad Berlijn is qua oppervlakte bijna negen keer zo groot als Parijs.",
  "Duitsland grenst aan negen landen — meer dan elk ander EU-land."],
 woorden:[["Pups","Duits","scheetje"],
  ["Quatsch","Duits","onzin"],
  ["Purzelbaum","Duits","koprol"],
  ["Ohrwurm","Duits","liedje dat in je hoofd blijft hangen (letterlijk: oorworm)"],
  ["Kummerspeck","Duits","kilo's die je aankomt van verdriet-eten (letterlijk: verdrietspek)"],
  ["Kacka","Duits","poep"]],
 fotos:[["Brandenburger Tor","Brandenburger Tor","nl"],["Slot Neuschwanstein","Slot Neuschwanstein","nl"],["Dom van Keulen","Dom van Keulen","nl"],["Rijksdaggebouw","Rijksdaggebouw","nl"],["East Side Gallery (Berlijnse Muur)","East Side Gallery","nl"],["Frauenkirche in Dresden","Frauenkirche (Dresden)","nl"],["Slot Heidelberg","Slot Heidelberg","nl"],["Zugspitze","Zugspitze","nl"],["Elbphilharmonie","Elbphilharmonie","nl"],["Porta Nigra","Porta Nigra","nl"]]},
FR:{
 feiten:[
  "De Eiffeltoren wordt 's zomers wel 15 cm langer, omdat het ijzer uitzet door de warmte.",
  "Frankrijk is het meest bezochte land ter wereld: zo'n 90 miljoen toeristen per jaar.",
  "Het Louvre is het grootste kunstmuseum ter wereld — daar hangt de Mona Lisa.",
  "Frankrijk heeft meer dan 350 kaassoorten: voor elke dag een andere!",
  "De croissant komt eigenlijk uit Oostenrijk, maar de Fransen maakten hem wereldberoemd.",
  "De Franse TGV is een van de snelste treinen ter wereld: recordrit 574 km per uur.",
  "De Mont Blanc is met 4806 meter de hoogste berg van West-Europa.",
  "De Tour de France bestaat al sinds 1903.",
  "Disneyland Parijs is het meest bezochte pretpark van Europa.",
  "Frankrijk is het grootste land van de Europese Unie."],
 woorden:[["prout","Frans","scheetje"],
  ["caca","Frans","poep"],
  ["pamplemousse","Frans","grapefruit (zeg maar eens snel: pam-ple-moes!)"],
  ["chouchou","Frans","lieveling"],
  ["rigolo","Frans","grappig"],
  ["pipi","Frans","plasje"]],
 fotos:[["Eiffeltoren","Eiffeltoren","nl"],["Louvre","Louvre (museum)","nl"],["Arc de Triomphe","Arc de Triomphe (Parijs)","nl"],["Notre-Dame van Parijs","Notre-Dame van Parijs","nl"],["Mont Saint-Michel","Mont Saint-Michel","nl"],["Kasteel van Versailles","Kasteel van Versailles","nl"],["Sacré-Cœur","Basiliek Sacré-Cœur van Montmartre","nl"],["Pont du Gard","Pont du Gard","nl"],["Kasteel van Chambord","Kasteel van Chambord","nl"],["Duin van Pilat","Dune du Pilat","nl"]]},
ES:{
 feiten:[
  "In Spanje is elk jaar La Tomatina: een mega-tomatengevecht met duizenden mensen.",
  "Aan de Sagrada Família in Barcelona wordt al sinds 1882 gebouwd — en hij is nog niet af.",
  "Met oud en nieuw eten Spanjaarden twaalf druiven, één bij elke klokslag.",
  "Spaans is na het Chinees de meest gesproken moedertaal ter wereld.",
  "Paella komt uit Valencia en wordt traditioneel met z'n allen uit één pan gegeten.",
  "In Spanje is de siësta beroemd: een rustpauze op het heetst van de dag.",
  "Camp Nou in Barcelona is het grootste voetbalstadion van Europa.",
  "Flamenco — muziek, handgeklap en dans — komt uit Zuid-Spanje.",
  "Het Alhambra in Granada was een paleis van sultans, vol prachtige patronen.",
  "Spanje heeft meer dan 8000 kilometer kust."],
 woorden:[["caca","Spaans","poep"],
  ["pedo","Spaans","scheet"],
  ["chachi","Spaans","supergaaf"],
  ["sacapuntas","Spaans","puntenslijper"],
  ["gafas","Spaans","bril"],
  ["mariposa","Spaans","vlinder"]],
 fotos:[["Sagrada Família","Sagrada Família","nl"],["Park Güell","Park Güell","nl"],["Alhambra","Alhambra (Granada)","nl"],["Koninklijk Paleis van Madrid","Koninklijk Paleis van Madrid","nl"],["Plaza Mayor in Madrid","Plaza Mayor (Madrid)","nl"],["Mezquita van Córdoba","Mezquita (Córdoba)","nl"],["Guggenheim Bilbao","Guggenheim Museum (Bilbao)","nl"],["Alcázar van Sevilla","Alcázar (Sevilla)","nl"]]},
PT:{
 feiten:[
  "In Lissabon vind je de oudste boekwinkel ter wereld — al open sinds 1732.",
  "Meer dan de helft van alle kurk ter wereld komt uit Portugal.",
  "Het pastel de nata-taartje is bedacht door monniken in Lissabon.",
  "Portugal en Engeland zijn al sinds 1373 bondgenoten — het oudste bondgenootschap ter wereld.",
  "De zeevaarder Vasco da Gama voer als eerste Europeaan naar India.",
  "Portugese huizen zijn vaak versierd met azulejos: beschilderde tegeltjes.",
  "De Vasco da Gamabrug bij Lissabon is ruim 17 kilometer lang.",
  "Lissabon is ouder dan Rome.",
  "In Nazaré surfen mensen op golven van meer dan 20 meter hoog.",
  "Portugal was ooit een wereldrijk met gebieden in Azië, Afrika en Zuid-Amerika."],
 woorden:[["pum","Portugees","scheetje"],
  ["cocô","Portugees","poep"],
  ["pipoca","Portugees","popcorn"],
  ["fofinho","Portugees","schattig"],
  ["borboleta","Portugees","vlinder"],
  ["saudade","Portugees","het gevoel dat je iets of iemand heel erg mist"]],
 fotos:[["Torre de Belém","Torre de Belém","nl"],["Jerónimosklooster","Jerónimosklooster","nl"],["Palácio da Pena","Palácio Nacional da Pena","nl"],["Ponte 25 de Abril","Ponte 25 de Abril","nl"],["Cabo da Roca","Cabo da Roca","nl"],["Livraria Lello","Livraria Lello","en"],["Ponte Dom Luís I","Ponte Dom Luís I","nl"],["Elevador de Santa Justa","Elevador de Santa Justa","nl"]]},
IT:{
 feiten:[
  "In de Trevi-fontein in Rome gooien mensen elke dag zo'n €3000 aan muntjes!",
  "Pizza is uitgevonden in Napels — de pizza margherita heeft de kleuren van de vlag.",
  "Italië heeft de meeste werelderfgoed-plekken van alle landen.",
  "De toren van Pisa staat scheef omdat de grond eronder te zacht is.",
  "Er bestaan meer dan 300 soorten pasta.",
  "In Venetië varen mensen door de straten: het zijn kanalen, met ruim 400 bruggen.",
  "Het Colosseum bood plaats aan ongeveer 50.000 toeschouwers.",
  "Ferrari en Lamborghini komen allebei uit Italië.",
  "IJs (gelato) zoals wij het kennen is in Italië uitgevonden.",
  "Rome bestaat al meer dan 2700 jaar."],
 woorden:[["puzzetta","Italiaans","scheetje"],
  ["cacca","Italiaans","poep"],
  ["pipistrello","Italiaans","vleermuis"],
  ["farfalla","Italiaans","vlinder"],
  ["che schifo!","Italiaans","wat vies!"],
  ["gattino","Italiaans","katje"]],
 fotos:[["Colosseum","Colosseum","nl"],["Toren van Pisa","Toren van Pisa","nl"],["Trevifontein","Trevifontein","nl"],["Dom van Milaan","Dom van Milaan","nl"],["San Marcoplein","San Marcoplein","nl"],["Rialtobrug","Rialtobrug","nl"],["Vesuvius","Vesuvius","nl"],["Pompeï","Pompeï","nl"],["Ponte Vecchio","Ponte Vecchio","nl"],["Forum Romanum","Forum Romanum","nl"]]},
GB:{
 feiten:[
  "Big Ben is niet de toren, maar de enorme bel die erin hangt.",
  "De soldaten van de Queen's Guard mogen tijdens hun dienst niet lachen.",
  "In Londen worden meer dan 300 talen gesproken.",
  "Britten drinken zo'n 100 miljoen koppen thee per dag.",
  "Stonehenge is ongeveer 5000 jaar oud — niemand weet precies waarvoor het diende.",
  "In het Verenigd Koninkrijk rijdt iedereen links.",
  "Volgens de legende woont in het Schotse Loch Ness een monster: Nessie.",
  "De koning is officieel eigenaar van de zwanen op de Theems.",
  "Modern voetbal is in Engeland uitgevonden.",
  "Harry Potter is geschreven door de Britse J.K. Rowling."],
 woorden:[["collywobbles","Engels","kriebels of zenuwen in je buik"],
  ["fart","Engels","scheet"],
  ["booger","Engels","snottebel"],
  ["gobbledygook","Engels","onbegrijpelijke wartaal"],
  ["flabbergasted","Engels","stomverbaasd"],
  ["bumblebee","Engels","hommel"]],
 fotos:[["Big Ben","Big Ben","nl"],["Tower Bridge","Tower Bridge","nl"],["Tower of London","Tower of London","nl"],["Buckingham Palace","Buckingham Palace","nl"],["Stonehenge","Stonehenge","nl"],["London Eye","London Eye","nl"],["Edinburgh Castle","Edinburgh Castle","nl"],["Windsor Castle","Windsor Castle","nl"],["Giant's Causeway","Giant's Causeway","nl"],["White Cliffs of Dover","Krijtrotsen van Dover","nl"]]},
IE:{
 feiten:[
  "In Ierland leven geen wilde slangen — helemaal nul!",
  "Halloween komt oorspronkelijk uit Ierland, van het oude feest Samhain.",
  "Er wonen meer mensen met Ierse voorouders buiten Ierland dan erin.",
  "Ierland wordt het Smaragdgroene Eiland genoemd, omdat het er zo groen is.",
  "Ierland is het enige land met een muziekinstrument als nationaal symbool: de harp.",
  "Op St. Patrick's Day kleurt de halve wereld groen — zelfs rivieren worden groen geverfd.",
  "De Cliffs of Moher zijn kliffen van ruim 200 meter hoog, recht boven de oceaan.",
  "Volgens Ierse verhalen verstoppen kabouters (leprechauns) potten met goud bij de regenboog.",
  "In Ierse pubs wordt vaak live volksmuziek gespeeld.",
  "Het Ierse Newgrange is ouder dan de piramides van Egypte."],
 woorden:[["banjaxed","Iers-Engels","helemaal kapot"],
  ["craic","Iers","plezier, gezelligheid (spreek uit: krek)"],
  ["púca","Iers","ondeugend spookje uit Ierse verhalen"],
  ["madra","Iers","hond"],
  ["féileacán","Iers","vlinder"]],
 fotos:[["Cliffs of Moher","Cliffs of Moher","nl"],["Trinity College Dublin","Trinity College (Dublin)","nl"],["Rock of Cashel","Rock of Cashel","nl"],["Dublin Castle","Dublin Castle","en"],["Ha'penny Bridge","Ha'penny Bridge","en"],["Newgrange","Newgrange","nl"],["Kylemore Abbey","Kylemore Abbey","en"]]},
AT:{
 feiten:[
  "Mozart kwam uit Oostenrijk en schreef zijn eerste muziek toen hij 5 jaar was.",
  "Bijna twee derde van Oostenrijk bestaat uit bergen.",
  "De oudste dierentuin ter wereld staat in Wenen: Tiergarten Schönbrunn, uit 1752.",
  "De schnitzel is het beroemdste gerecht van Wenen.",
  "In Oostenrijk bestaat een dorpje dat écht Fucking heette — het heet nu Fugging.",
  "Het reuzenrad in het Prater draait al sinds 1897.",
  "De Grossglockner is met 3798 meter de hoogste berg van Oostenrijk.",
  "Oostenrijk heeft geen zee, maar wel honderden bergmeren.",
  "Skiën is er volkssport nummer één — veel kinderen leren het op school.",
  "The Sound of Music speelt zich af in Salzburg."],
 woorden:[["Oachkatzlschwoaf","Oostenrijks","eekhoornstaartje — een echte tongbreker!"],
  ["Palatschinken","Oostenrijks","pannenkoeken (nee, geen ham!)"],
  ["Busserl","Oostenrijks","kusje"],
  ["Sackerl","Oostenrijks","zakje"],
  ["Marille","Oostenrijks","abrikoos"]],
 fotos:[["Slot Schönbrunn","Slot Schönbrunn","nl"],["Stephansdom","Stephansdom (Wenen)","nl"],["Hofburg","Hofburg","nl"],["Wiener Riesenrad","Wiener Riesenrad","nl"],["Slot Belvedere","Slot Belvedere","nl"],["Grossglockner","Grossglockner","nl"],["Hallstatt","Hallstatt","nl"],["Goldenes Dachl","Goldenes Dachl","nl"]]},
CH:{
 feiten:[
  "In Zwitserland mag je niet één cavia hebben: ze zijn zó sociaal dat het er minstens twee moeten zijn.",
  "Zwitserland heeft vier officiële talen: Duits, Frans, Italiaans en Reto-Romaans.",
  "De gaten in Zwitserse kaas ontstaan door bacteriën die belletjes maken.",
  "Zwitserland is beroemd om horloges: de duurste ter wereld komen hiervandaan.",
  "De Matterhorn is een van de beroemdste bergen ter wereld — hij staat op de Toblerone-verpakking.",
  "Zwitserland heeft meer dan 1500 meren.",
  "Melkchocolade is in Zwitserland uitgevonden.",
  "Zwitserland is al meer dan 200 jaar neutraal en deed aan geen enkele oorlog mee.",
  "Er zijn zoveel bunkers dat álle Zwitsers er tegelijk in zouden passen.",
  "De langste treintunnel ter wereld ligt in Zwitserland: de Gotthard-basistunnel van 57 km."],
 woorden:[["Chuchichäschtli","Zwitserduits","keukenkastje"],
  ["Büsi","Zwitserduits","poesje"],
  ["Grüezi","Zwitserduits","goedendag"],
  ["Furz","Duits","scheet"],
  ["Znüni","Zwitserduits","tussendoortje om 9 uur"]],
 fotos:[["Matterhorn","Matterhorn","nl"],["Kapellbrücke","Kapellbrücke","nl"],["Jet d'Eau","Jet d'eau","nl"],["Slot Chillon","Slot Chillon","nl"],["Jungfraujoch","Jungfraujoch","nl"],["Bundeshaus","Bundeshaus (Bern)","nl"],["Aletschgletsjer","Aletschgletsjer","nl"],["Zytglogge","Zytglogge","nl"]]},
DK:{
 feiten:[
  "LEGO komt uit Denemarken: 'leg godt' betekent 'speel goed'.",
  "Denemarken bestaat uit meer dan 400 eilanden.",
  "De Deense vlag is de oudste vlag ter wereld die nog wordt gebruikt.",
  "Sprookjesschrijver Hans Christian Andersen (De kleine zeemeermin) was een Deen.",
  "Denen horen bij de gelukkigste mensen ter wereld — mede dankzij 'hygge': gezelligheid.",
  "Het hoogste punt van Denemarken is maar 171 meter — vlakker dan je denkt!",
  "In Denemarken fietsen mensen bijna net zo veel als in Nederland.",
  "Tivoli in Kopenhagen is een van de oudste pretparken ter wereld (1843).",
  "De Sontbrug verbindt Denemarken met Zweden: eerst brug, dan tunnel.",
  "Groenland, het grootste eiland ter wereld, hoort bij het Deense koninkrijk."],
 woorden:[["prut","Deens","scheet — echt waar, zo heet dat daar!"],
  ["bæ","Deens","poep"],
  ["slik","Deens","snoep (een slikbutik is een snoepwinkel!)"],
  ["fart","Deens","snelheid — in Deense liften staat 'i fart': in beweging"],
  ["hyggelig","Deens","gezellig"],
  ["sommerfugl","Deens","vlinder (letterlijk: zomervogel)"]],
 fotos:[["De kleine zeemeermin","De kleine zeemeermin (beeld)","nl"],["Nyhavn","Nyhavn","nl"],["Tivoli","Tivoli (Kopenhagen)","nl"],["Kasteel Kronborg","Kronborg","nl"],["Amalienborg","Amalienborg","nl"],["Kasteel Rosenborg","Kasteel Rosenborg","nl"],["Legoland Billund","Legoland Billund","en"],["Sontbrug","Sontbrug","nl"]]},
NO:{
 feiten:[
  "In Noord-Noorwegen gaat de zon 's zomers wékenlang niet onder: de middernachtzon.",
  "Noorwegen heeft meer dan 1000 fjorden: diepe zeearmen tussen de bergen.",
  "In de winter zie je er vaak het noorderlicht: dansende groene lichten aan de hemel.",
  "De kustlijn van Noorwegen is met alle inhammen ruim 100.000 km lang — 2,5 rondje om de aarde.",
  "Bijna alle nieuwe auto's in Noorwegen zijn elektrisch.",
  "De Vikingen kwamen uit Noorwegen, Zweden en Denemarken.",
  "Noorwegen gaf de kerstboom op Trafalgar Square in Londen — elk jaar weer, als bedankje.",
  "Op de eilandengroep Spitsbergen leven meer ijsberen dan mensen.",
  "Noorwegen is bijna 2000 kilometer lang, maar op het smalste punt maar 1,6 km breed.",
  "De trollen uit sprookjes komen uit Noorse verhalen."],
 woorden:[["promp","Noors","scheet"],
  ["bæsj","Noors","poep"],
  ["kos","Noors","knus en gezellig"],
  ["rar","Noors","vreemd, raar"],
  ["sommerfugl","Noors","vlinder"],
  ["fjert","Noors","windje"]],
 fotos:[["Geirangerfjord","Geirangerfjord","nl"],["Preikestolen","Preikestolen","nl"],["Bryggen in Bergen","Bryggen","nl"],["Noordkaap","Noordkaap (Noorwegen)","nl"],["Staafkerk van Borgund","Staafkerk van Borgund","nl"],["Operahuis van Oslo","Operahuis van Oslo","nl"],["Trolltunga","Trolltunga","en"],["Atlanterhavsveien","Atlanterhavsveien","en"]]},
SE:{
 feiten:[
  "Alle IKEA-namen zijn echte Zweedse woorden en plaatsnamen.",
  "In Zweden ligt een hotel dat elk jaar opnieuw van ijs wordt gebouwd.",
  "Zweden heeft bijna 100.000 meren.",
  "Fika is heilig in Zweden: even pauze met koffie of limonade en iets lekkers.",
  "In Zweedse bossen leven elanden — ze zijn groter dan een paard.",
  "De Nobelprijzen worden elk jaar uitgereikt in Stockholm.",
  "Pippi Langkous is bedacht door de Zweedse Astrid Lindgren.",
  "Stockholm is gebouwd op 14 eilanden.",
  "Minecraft is gemaakt in Zweden.",
  "In Noord-Zweden kun je in de winter over bevroren meren schaatsen en met sledehonden rijden."],
 woorden:[["bajs","Zweeds","poep"],
  ["prutt","Zweeds","scheet"],
  ["fika","Zweeds","gezellige pauze met iets lekkers"],
  ["kaka","Zweeds","koekje (echt waar!)"],
  ["fjäril","Zweeds","vlinder"],
  ["smultronställe","Zweeds","je geheime lievelingsplekje (letterlijk: wilde-aardbeienplek)"]],
 fotos:[["Stadhuis van Stockholm","Stadhuis van Stockholm","nl"],["Gamla stan","Gamla stan","nl"],["Vasamuseum","Vasamuseet","nl"],["Icehotel","Icehotel","en"],["Slot Drottningholm","Slot Drottningholm","nl"],["Turning Torso","Turning Torso","nl"],["Ales stenar","Ales stenar","nl"],["Skansen","Skansen","nl"]]},
FI:{
 feiten:[
  "Finland heeft ruim 3 miljoen sauna's — op maar 5,5 miljoen mensen!",
  "Finland wordt het land van de duizend meren genoemd, maar het zijn er bijna 188.000.",
  "Volgens de Finnen woont de Kerstman in Fins Lapland, op de berg Korvatunturi.",
  "In Finland zijn de wereldkampioenschappen vrouw-dragen én luchtgitaar spelen.",
  "Angry Birds komt uit Finland.",
  "In Lapland rennen meer rendieren rond dan er mensen wonen.",
  "Finland is volgens onderzoeken het gelukkigste land ter wereld.",
  "In de winter kan het er kouder worden dan −40 graden.",
  "De Mumins (Moomin) zijn bedacht door de Finse Tove Jansson.",
  "Fins lijkt op geen enkele buurtaal: het is familie van het Hongaars en Estisch."],
 woorden:[["pieru","Fins","scheet"],
  ["kakka","Fins","poep"],
  ["hassu","Fins","grappig"],
  ["sisu","Fins","nooit opgeven, altijd doorzetten"],
  ["perhonen","Fins","vlinder"],
  ["kissa","Fins","kat"]],
 fotos:[["Dom van Helsinki","Dom van Helsinki","nl"],["Suomenlinna","Suomenlinna","nl"],["Santa Claus Village","Santa Claus Village","en"],["Olavinlinna","Olavinlinna","nl"],["Temppeliaukiokerk","Temppeliaukio Church","en"],["Uspenskikathedraal","Uspenskikathedraal (Helsinki)","nl"]]},
PL:{
 feiten:[
  "In de stad Wrocław staan honderden kleine kabouterbeeldjes verstopt.",
  "De oudste zoutmijn van Europa, Wieliczka, heeft ondergronds zelfs een kerk van zout.",
  "Marie Curie, twee keer Nobelprijswinnaar, kwam uit Warschau.",
  "Het oude centrum van Warschau is na de oorlog steen voor steen herbouwd.",
  "In het Poolse oerbos Białowieża leven nog wilde wisenten.",
  "Pierogi — gevulde deegkussentjes — zijn hét nationale gerecht.",
  "Polen is de grootste appelproducent van Europa.",
  "In Polen ligt een bos met honderden kromme bomen — niemand weet precies waarom ze krom zijn.",
  "Astronoom Copernicus, die ontdekte dat de aarde om de zon draait, was een Pool.",
  "Het woord 'spruitjes' klinkt saai, maar Polen is dol op zuurkool en komkommers uit het vat."],
 woorden:[["kupa","Pools","poep"],
  ["pierdnięcie","Pools","scheet (probeer dát maar eens te zeggen)"],
  ["chrząszcz","Pools","kever — beruchte tongbreker!"],
  ["motylek","Pools","vlindertje"],
  ["żółw","Pools","schildpad"]],
 fotos:[["Wawel","Wawel","nl"],["Oude Stad van Warschau","Oude Stad (Warschau)","nl"],["Kasteel Malbork","Malbork (kasteel)","nl"],["Sukiennice","Sukiennice","nl"],["Wieliczka-zoutmijn","Zoutmijn van Wieliczka","nl"],["Morskie Oko","Morskie Oko","nl"],["Paleis van Cultuur en Wetenschap","Paleis van Cultuur en Wetenschap","nl"]]},
CZ:{
 feiten:[
  "De astronomische klok in Praag is uit 1410 — en hij doet het nog steeds.",
  "Tsjechen zijn wereldkampioen bier drinken (per persoon) — maar limonade telt daar niet mee!",
  "De Karelsbrug in Praag staat vol met 30 standbeelden.",
  "Het woord 'robot' is bedacht door de Tsjechische schrijver Karel Čapek.",
  "De Praagse burcht is het grootste oude kasteelcomplex ter wereld.",
  "Suikerklontjes zijn uitgevonden in Tsjechië.",
  "Contactlenzen zijn uitgevonden door een Tsjech.",
  "Tsjechië heeft meer dan 2000 kastelen en burchten.",
  "De mol uit de tekenfilm ('Krtek') is een beroemde Tsjech.",
  "In Tsjechië ligt een kerk versierd met duizenden echte botten: de botkapel van Sedlec."],
 woorden:[["prd","Tsjechisch","scheet (ja, één woordje zonder klinker!)"],
  ["hovínko","Tsjechisch","drolletje"],
  ["strč prst skrz krk","Tsjechisch","'steek je vinger door je keel' — hele zin zonder klinkers!"],
  ["brouk","Tsjechisch","kever"],
  ["kočka","Tsjechisch","kat"]],
 fotos:[["Karelsbrug","Karelsbrug","nl"],["Praagse burcht","Praagse burcht","nl"],["Praags astronomisch uurwerk","Praags astronomisch uurwerk","nl"],["Oudestadsplein","Oudestadsplein (Praag)","nl"],["Český Krumlov","Český Krumlov","nl"],["Karlštejn","Karlštejn (kasteel)","nl"],["Dansende Huis","Dancing House","en"]]},
GR:{
 feiten:[
  "De Olympische Spelen zijn bijna 3000 jaar geleden in Griekenland uitgevonden.",
  "Democratie — het volk beslist mee — is bedacht in het oude Athene.",
  "Griekenland heeft zo'n 6000 eilanden; op ongeveer 220 wonen mensen.",
  "Het Griekse alfabet bestaat al bijna 3000 jaar: alfa, bèta, gamma…",
  "De marathon heet naar het Griekse plaatsje Marathon, 42 km van Athene.",
  "De oude Grieken bedachten het theater: komedies en tragedies.",
  "Griekenland heeft ongeveer 300 dagen zon per jaar.",
  "Grieken eten de meeste kaas van heel Europa — vooral feta.",
  "Veel wetenschapswoorden komen uit het Grieks, zoals 'telefoon': ver + geluid.",
  "De Akropolis van Athene is meer dan 2400 jaar oud."],
 woorden:[["papáki","Grieks","eendje — zo noemen Grieken het @-teken!"],
  ["klaniá","Grieks","scheet"],
  ["kaká","Grieks","poep"],
  ["gáta","Grieks","kat"],
  ["petalouda","Grieks","vlinder"]],
 fotos:[["Akropolis van Athene","Akropolis van Athene","nl"],["Parthenon","Parthenon (Athene)","nl"],["Meteora","Meteora (Griekenland)","nl"],["Santorini","Santorini","nl"],["Olympia","Olympia (Griekenland)","nl"],["Delphi","Delphi (Griekenland)","nl"],["Windmolens van Mykonos","Mykonos","nl"],["Witte Toren van Thessaloniki","Witte Toren (Thessaloniki)","nl"]]},
HU:{
 feiten:[
  "De Rubiks kubus is bedacht door de Hongaar Ernő Rubik.",
  "Boedapest heeft meer dan 100 warmwaterbronnen — je kunt er buiten badderen, zelfs in de winter.",
  "Boedapest was ooit twee steden: Buda en Pest, aan weerszijden van de Donau.",
  "De balpen is uitgevonden door de Hongaar László Bíró.",
  "Het Balatonmeer is het grootste meer van Midden-Europa: de 'Hongaarse zee'.",
  "Hongaars is superlastig: het heeft wel 14 klinkers.",
  "Paprikapoeder is hét Hongaarse kruid — het zit in bijna elk gerecht, zoals goulash.",
  "De metro van Boedapest is de oudste van het Europese vasteland (1896).",
  "Het Hongaarse parlementsgebouw heeft 691 kamers.",
  "Vitamine C werd ontdekt door een Hongaarse wetenschapper — in paprika's!"],
 woorden:[["kaki","Hongaars","poep"],
  ["fing","Hongaars","scheet"],
  ["puszi","Hongaars","kusje (spreek uit: poesie!)"],
  ["cica","Hongaars","poes"],
  ["pillangó","Hongaars","vlinder"]],
 fotos:[["Hongaars parlementsgebouw","Hongaars parlementsgebouw","nl"],["Kettingbrug","Széchenyi-kettingbrug","nl"],["Vissersbastion","Vissersbastion","nl"],["Burchtpaleis van Boedapest","Buda Castle","en"],["Heldenplein","Hősök tere","en"],["Balatonmeer","Balatonmeer","nl"]]},
HR:{
 feiten:[
  "Dalmatiërs — de witte honden met zwarte stippen — komen uit Dalmatië in Kroatië.",
  "De stropdas is een Kroatische uitvinding: 'cravate' komt van 'Croate'.",
  "De oude stad Dubrovnik was decor voor King's Landing in een beroemde tv-serie.",
  "Kroatië heeft meer dan 1200 eilanden.",
  "In de Plitvicemeren stromen 16 meren via watervallen in elkaar over.",
  "In Pula staat een bijna compleet Romeins amfitheater, klein broertje van het Colosseum.",
  "Het strand van Zlatni Rat verandert van vorm door de wind en golven.",
  "In Zagreb rijdt een van de kortste kabelspoorwegen ter wereld: 66 meter.",
  "Nikola Tesla, de beroemde uitvinder, werd geboren in wat nu Kroatië is."],
 woorden:[["prdac","Kroatisch","scheet"],
  ["kakica","Kroatisch","poepje"],
  ["leptir","Kroatisch","vlinder"],
  ["pas","Kroatisch","hond"],
  ["mačka","Kroatisch","kat"]],
 fotos:[["Dubrovnik","Dubrovnik","nl"],["Plitvicemeren","Nationaal park Plitvicemeren","nl"],["Paleis van Diocletianus","Paleis van Diocletianus","nl"],["Arena van Pula","Arena van Pula","nl"],["Kathedraal van Zagreb","Kathedraal van Zagreb","nl"],["Nationaal park Krka","Nationaal park Krka","nl"]]},
IS:{
 feiten:[
  "Op IJsland zijn geen muggen — en veel IJslanders geloven in elfjes.",
  "IJsland heeft meer dan 130 vulkanen; om de paar jaar barst er wel één uit.",
  "Warm water komt er zó uit de grond: huizen worden verwarmd met vulkaanwarmte.",
  "IJslanders hebben meestal geen achternaam, maar heten 'zoon van' of 'dochter van' hun vader.",
  "De Geysir op IJsland gaf zijn naam aan alle geisers ter wereld.",
  "Op IJsland leven ongeveer 800.000 papegaaiduikers — meer vogels dan mensen!",
  "IJsland heeft geen leger.",
  "Het parlement van IJsland, de Althing, bestaat al sinds het jaar 930.",
  "In de winter is het er maar 4-5 uur per dag licht, in de zomer bijna altijd.",
  "IJslandse paarden hebben een extra loopje dat andere paarden niet kennen: de tölt."],
 woorden:[["prump","IJslands","scheet"],
  ["kúkur","IJslands","poep"],
  ["fiðrildi","IJslands","vlinder"],
  ["köttur","IJslands","kat"],
  ["þetta reddast","IJslands","komt wel goed! (het IJslandse levensmotto)"]],
 fotos:[["Hallgrímskirkja","Hallgrímskirkja","nl"],["Gullfoss","Gullfoss","nl"],["Geysir","Geysir","nl"],["Blue Lagoon","Blue Lagoon (geothermal spa)","en"],["Thingvellir","Nationaal park Þingvellir","nl"],["Jökulsárlón","Jökulsárlón","nl"],["Kirkjufell","Kirkjufell","en"]]},
EE:{
 feiten:[
  "Estland heeft meer dan 2000 eilanden en bijna overal gratis wifi.",
  "Esten kunnen via internet stemmen bij verkiezingen — als eerste land ter wereld.",
  "Skype is bedacht door programmeurs uit Estland.",
  "De helft van Estland is bos; er leven beren, wolven en lynxen.",
  "Tallinn heeft een van de best bewaarde middeleeuwse binnensteden van Europa.",
  "In Estland is 'zingen' bijna een sport: op het Zangfeest zingen tienduizenden mensen samen.",
  "Estisch is familie van het Fins — en heeft woorden met wel vier klinkers achter elkaar."],
 woorden:[["kakk","Estisch","uil (klinkt als iets anders, hè?)"],
  ["jäääär","Estisch","rand van het ijs — vier keer een a-klank achter elkaar!"],
  ["öö","Estisch","nacht (alleen maar ö's!)"],
  ["liblikas","Estisch","vlinder"],
  ["kass","Estisch","kat"]],
 fotos:[["Oude stad van Tallinn","Tallinn","nl"],["Alexander Nevski-kathedraal","Alexander Nevski-kathedraal (Tallinn)","nl"],["Toompea","Toompea","nl"],["Kadriorg-paleis","Kadriorg Palace","en"],["Pikk Hermann","Pikk Hermann","en"]]},
LV:{
 feiten:[
  "De Ventas Rumba in Letland is de breedste waterval van Europa: bijna 250 meter!",
  "Riga staat vol jugendstilhuizen met gezichten en figuren op de gevels.",
  "Volgens de Letten is de kerstboom in 1510 voor het eerst in Riga versierd.",
  "Meer dan de helft van Letland is bos.",
  "Letland heeft een van de snelste internetverbindingen van Europa.",
  "Het Vrijheidsmonument in Riga wordt dag en nacht bewaakt door erewachten.",
  "Letten vieren midzomernacht (Jāņi) met bloemenkransen en vuren die de hele nacht branden."],
 woorden:[["puņķi","Lets","snottebellen"],
  ["burbulis","Lets","luchtbel"],
  ["taurenis","Lets","vlinder"],
  ["kaķis","Lets","kat"]],
 fotos:[["Huis van de Zwarthoofden","House of the Blackheads (Riga)","en"],["Vrijheidsmonument","Freedom Monument","en"],["Dom van Riga","Dom van Riga","nl"],["Rundāle-paleis","Rundāle Palace","en"],["Kasteel van Turaida","Turaida Castle","en"]]},
LT:{
 feiten:[
  "In de wijk Užupis in Vilnius geldt een eigen grondwet met: 'Iedere hond heeft het recht om hond te zijn.'",
  "Op de Kruisenheuvel staan meer dan 100.000 kruisen — al bijna 200 jaar brengen mensen ze erheen.",
  "Litouwen was ooit een van de grootste landen van Europa.",
  "Basketbal is dé nationale sport; het kleine Litouwen wint vaak van grote landen.",
  "Het geografisch middelpunt van Europa ligt (volgens Franse rekenaars) in Litouwen.",
  "Litouwers houden van cepelinai: enorme aardappelknoedels in de vorm van een zeppelin.",
  "Het kasteel van Trakai staat midden op een eiland in een meer."],
 woorden:[["bezdalas","Litouws","scheet"],
  ["drugelis","Litouws","vlinder"],
  ["katė","Litouws","kat"],
  ["labas","Litouws","hoi"]],
 fotos:[["Kasteel van Trakai","Trakai Island Castle","en"],["Gediminas-toren","Gediminas' Tower","en"],["Kruisenheuvel","Hill of Crosses","en"],["Kathedraal van Vilnius","Kathedraal van Vilnius","nl"],["Poort van de Dageraad","Poort van de Dageraad","nl"]]},
SK:{
 feiten:[
  "Slowakije heeft meer dan 6000 grotten — een gatenkaas onder de grond.",
  "In Slowakije staan honderden kastelen; de Spišburcht is een van de grootste van Europa.",
  "De Donau stroomt door de hoofdstad Bratislava.",
  "Bratislava en Wenen zijn de twee dichtstbijzijnde hoofdsteden van Europa: 60 km.",
  "In de Hoge Tatra leven bruine beren, wolven en gemzen.",
  "Slowakije maakt de meeste auto's per inwoner van de hele wereld.",
  "Het ijshockeyteam is de nationale trots."],
 woorden:[["bublina","Slowaaks","zeepbel"],
  ["prd","Slowaaks","scheet"],
  ["zmrzlina","Slowaaks","ijsje (probeer maar eens te bestellen!)"],
  ["motýľ","Slowaaks","vlinder"]],
 fotos:[["Burcht van Bratislava","Burcht van Bratislava","nl"],["Spišburcht","Spiš Castle","en"],["Kasteel van Bojnice","Bojnice Castle","en"],["Hoge Tatra","Hoge Tatra","nl"],["UFO-brug","Most SNP","en"]]},
SI:{
 feiten:[
  "In de Postojna-grot leven 'babydraakjes': blinde roze salamanders die 100 jaar oud worden.",
  "Bijna 60% van Slovenië is bos; er leven zo'n duizend bruine beren.",
  "Midden in het Meer van Bled ligt een eilandje met een kerkje — je vaart erheen in een houten bootje.",
  "Slovenië heeft maar 47 kilometer kust, maar wel bergen, grotten én wijngaarden.",
  "In Ljubljana waken draken over de stad — ze staan op de Drakenbrug.",
  "Slovenië was het eerste land met een compleet rookvrij binnenland? Nee — maar wél het eerste met een eigen bijenfeestdag: bijen zijn er heilig.",
  "De berg Triglav staat zelfs in de Sloveense vlag."],
 woorden:[["prdec","Sloveens","scheet"],
  ["kakec","Sloveens","poepje"],
  ["metulj","Sloveens","vlinder"],
  ["muca","Sloveens","poesje"]],
 fotos:[["Meer van Bled","Meer van Bled","nl"],["Grotten van Postojna","Grotten van Postojna","nl"],["Kasteel van Predjama","Predjama Castle","en"],["Drakenbrug","Dragon Bridge (Ljubljana)","en"],["Triglav","Triglav","nl"]]},
BA:{
 feiten:[
  "In Bosnië ligt Perućica, een van de allerlaatste oerbossen van Europa.",
  "De beroemde witte brug Stari Most in Mostar is 400 jaar oud; jongens duiken er 24 meter vanaf.",
  "Sarajevo was in 1984 gastheer van de Olympische Winterspelen.",
  "In Sarajevo kun je koffie drinken zoals honderden jaren geleden: uit koperen kannetjes.",
  "Bosnië heeft maar ongeveer 20 kilometer kust — het kortste kuststrookje van Europa op Monaco na.",
  "Bij Visoko liggen heuvels waarvan sommige mensen denken dat het oude piramides zijn.",
  "De naam Bosnië komt van de rivier de Bosna."],
 woorden:[["guza","Bosnisch","billen"],
  ["prdež","Bosnisch","scheet"],
  ["buba","Bosnisch","kevertje"],
  ["leptir","Bosnisch","vlinder"]],
 fotos:[["Stari Most","Stari most","nl"],["Baščaršija","Baščaršija","en"],["Kravica-watervallen","Kravica (waterfall)","en"],["Mehmed Paša Sokolović-brug","Mehmed Paša Sokolović Bridge","en"],["Vrelo Bosne","Vrelo Bosne","en"]]},
RS:{
 feiten:[
  "Servië is een van de grootste frambozenlanden ter wereld — miljoenen kilo's per jaar!",
  "Belgrado ligt waar twee grote rivieren samenkomen: de Donau en de Sava.",
  "De beroemde uitvinder Nikola Tesla is de nationale held; het vliegveld heet naar hem.",
  "Belgrado is een van de oudste steden van Europa: mensen wonen er al 7000 jaar.",
  "In het dorpje Drvengrad is een compleet houten sprookjesdorp gebouwd.",
  "De Sint-Savakerk in Belgrado is een van de grootste orthodoxe kerken ter wereld.",
  "Servische tennissers, zoals Novak Djokovic, horen bij de beste ter wereld."],
 woorden:[["prdež","Servisch","scheet"],
  ["kaka","Servisch","poep"],
  ["leptir","Servisch","vlinder"],
  ["mačka","Servisch","kat"]],
 fotos:[["Vesting van Belgrado","Belgrade Fortress","en"],["Sint-Savakerk","Church of Saint Sava","en"],["Skadarlija","Skadarlija","en"],["Golubac-vesting","Golubac Fortress","en"],["Đavolja Varoš","Đavolja Varoš","en"]]},
ME:{
 feiten:[
  "Montenegro betekent 'zwarte berg': 's ochtends skiën en 's middags zwemmen in zee kan er allebei.",
  "De Baai van Kotor lijkt op een fjord, maar ligt aan de Middellandse Zee.",
  "De Tara-kloof is de diepste kloof van Europa: tot 1300 meter diep.",
  "Montenegro heeft maar zo'n 620.000 inwoners — minder dan Rotterdam.",
  "Het eilandje Sveti Stefan is één groot hotel geworden.",
  "In het Skadarmeer, het grootste meer van de Balkan, leven pelikanen.",
  "Kotor heeft stadsmuren die hoog de berg op kronkelen — met 1350 traptreden."],
 woorden:[["njuška","Montenegrijns","snuitje"],
  ["guza","Montenegrijns","billen"],
  ["riba","Montenegrijns","vis"],
  ["leptir","Montenegrijns","vlinder"]],
 fotos:[["Kotor","Kotor","nl"],["Sveti Stefan","Sveti Stefan","en"],["Klooster Ostrog","Ostrog Monastery","en"],["Durmitor","Durmitor","nl"],["Baai van Kotor","Baai van Kotor","nl"]]},
XK:{
 feiten:[
  "Kosovo is het jongste land van Europa (2008) — de helft van de mensen is jonger dan 30.",
  "In Pristina staat het NEWBORN-monument: grote letters die elk jaar opnieuw worden beschilderd.",
  "Kosovo heeft een eigen 'bergreus': de 2656 meter hoge Gjeravica.",
  "De nationale bibliotheek van Kosovo wordt een van de aparts uitziende gebouwen ter wereld genoemd.",
  "Judoka Majlinda Kelmendi won voor Kosovo de allereerste olympische medaille: meteen goud!",
  "In Kosovo drinken vrienden samen macchiato — de koffiecultuur is er beroemd.",
  "Moeder Teresa had Albanese wortels en woonde als kind vlakbij Kosovo."],
 woorden:[["flutur","Albanees","vlinder"],
  ["pordhë","Albanees","scheet"],
  ["mace","Albanees","kat"],
  ["qen","Albanees","hond"]],
 fotos:[["Nationale bibliotheek van Kosovo","National Library of Kosovo","en"],["NEWBORN-monument","Newborn (monument)","en"],["Prizren","Prizren","nl"],["Klooster Gračanica","Gračanica Monastery","en"]]},
AL:{
 feiten:[
  "In Albanië staan meer dan 170.000 kleine bunkers verspreid — als betonnen paddenstoelen.",
  "Albanezen knikken van nee en schudden van ja — precies andersom dan bij ons!",
  "De adelaar op de vlag heeft twee koppen; Albanië noemt zichzelf 'land van de adelaars'.",
  "In Albanië rijden opvallend veel oude Mercedessen.",
  "De Albanese Rivièra heeft stranden die net zo mooi zijn als die van Griekenland.",
  "Berat heet 'de stad van de duizend vensters'.",
  "Het 'blauwe oog' is een bron met kraakhelder blauw water waarvan niemand de diepte kent."],
 woorden:[["pordhë","Albanees","scheet"],
  ["flutur","Albanees","vlinder"],
  ["papagall","Albanees","papegaai"],
  ["mace","Albanees","kat"]],
 fotos:[["Berat","Berat","nl"],["Gjirokastër","Gjirokastër","nl"],["Skanderbegplein","Skanderbeg Square","en"],["Krujë","Krujë","en"],["Ksamil","Ksamil","en"]]},
MK:{
 feiten:[
  "Het Ohridmeer is misschien wel het oudste meer van Europa: 1 tot 3 miljoen jaar oud.",
  "In Skopje staan honderden standbeelden — de stad is er vol mee gezet.",
  "Moeder Teresa werd geboren in Skopje.",
  "Aan het Ohridmeer stond ooit een van de eerste universiteiten van Europa.",
  "Noord-Macedonië heeft een 66 meter hoog kruis op een berg boven Skopje staan.",
  "Het Macedonische alfabet is cyrillisch, net als het Russische.",
  "In de Matka-kloof kun je kanoën tussen hoge rotswanden en grotten."],
 woorden:[["polžav","Macedonisch","slak"],
  ["prdež","Macedonisch","scheet"],
  ["peperutka","Macedonisch","vlinder"],
  ["kuče","Macedonisch","hondje"]],
 fotos:[["Ohrid","Ohrid","nl"],["Sint-Jan van Kaneo","Church of St. John at Kaneo","en"],["Stenen brug van Skopje","Stone Bridge (Skopje)","en"],["Millenniumkruis","Millennium Cross","en"],["Matka-kloof","Matka Canyon","en"]]},
BG:{
 feiten:[
  "Bulgarije is wereldkampioen rozenolie — die zit in bijna alle parfums.",
  "Bulgaren schudden van ja en knikken van nee — andersom dan bij ons!",
  "Het cyrillische alfabet is in Bulgarije bedacht, door de broers Cyrillus en Methodius.",
  "Bulgaarse yoghurt is wereldberoemd; het bacterietje erin heet 'bulgaricus'.",
  "Bulgarije is het oudste land van Europa dat nooit van naam veranderde (sinds 681).",
  "In maart geven Bulgaren elkaar rood-witte armbandjes (martenitsa) voor geluk.",
  "De Belogradchik-rotsen zien eruit als versteende reuzen en kastelen."],
 woorden:[["prǎdnja","Bulgaars","scheet"],
  ["kaka","Bulgaars","grote zus (echt waar!)"],
  ["peperuda","Bulgaars","vlinder"],
  ["kotka","Bulgaars","kat"]],
 fotos:[["Alexander Nevski-kathedraal","Alexander Nevski-kathedraal (Sofia)","nl"],["Rilaklooster","Rilaklooster","nl"],["Romeins theater van Plovdiv","Roman theatre of Plovdiv","en"],["Belogradchik-rotsen","Belogradchik Rocks","en"],["Tsarevets","Tsarevets (fortress)","en"]]},
RO:{
 feiten:[
  "In Roemenië staat het 'Dracula-kasteel' Bran, hoog op een rots in Transsylvanië.",
  "Het parlementspaleis in Boekarest is het zwaarste gebouw ter wereld.",
  "In de Karpaten leven de meeste bruine beren van Europa: zo'n 6000.",
  "De Transfăgărășan wordt een van de mooiste bergwegen ter wereld genoemd.",
  "In het dorp Săpânța ligt een 'vrolijk kerkhof' met gekleurde, grappige grafborden.",
  "De Donau eindigt in Roemenië in een enorme delta vol pelikanen.",
  "Roemeens lijkt op Italiaans en Frans: het is een Romaanse taal midden tussen Slavische buren."],
 woorden:[["pârț","Roemeens","scheet (spreek uit: purts!)"],
  ["caca","Roemeens","poep"],
  ["fluture","Roemeens","vlinder"],
  ["pisică","Roemeens","kat"]],
 fotos:[["Kasteel Bran","Kasteel Bran","nl"],["Kasteel Peleș","Kasteel Peleș","nl"],["Parlementspaleis","Palace of the Parliament","en"],["Transfăgărășan","Transfăgărășan","en"],["Sighișoara","Sighișoara","nl"],["Voroneț-klooster","Voroneț Monastery","en"]]},
MD:{
 feiten:[
  "In Moldavië ligt de grootste wijnkelder ter wereld: 200 km aan gangen — je rijdt er met de auto doorheen!",
  "Moldavië is een van de minst bezochte landen van Europa — een echt geheimpje dus.",
  "Bij Orheiul Vechi wonen monniken al eeuwen in grotten in een rotswand.",
  "De taal van Moldavië is Roemeens.",
  "Moldavië heeft een eigen 'mini-land' binnen de grenzen: Transnistrië, dat bijna niemand erkent.",
  "Het land is beroemd om zijn druiven; overal zie je wijngaarden.",
  "Moldavische huizen hebben vaak felgekleurde poorten met veel versieringen."],
 woorden:[["bâzdâganie","Moldavisch/Roemeens","raar wezen, gek ding"],
  ["pârț","Roemeens","scheet"],
  ["fluture","Roemeens","vlinder"],
  ["pisică","Roemeens","kat"]],
 fotos:[["Orheiul Vechi","Orheiul Vechi","en"],["Wijnkelder Mileștii Mici","Mileștii Mici","en"],["Fort van Soroca","Soroca Fort","en"],["Kathedraal van Chisinau","Nativity Cathedral, Chișinău","en"]]},
UA:{
 feiten:[
  "Oekraïne is het grootste land dat hélemaal in Europa ligt — vol zonnebloemvelden.",
  "Oekraïne wordt de graanschuur van Europa genoemd: de zwarte aarde is supervruchtbaar.",
  "In Kiev glanzen kerken met gouden koepels in de zon.",
  "De 'Tunnel van de Liefde' is een spoorlijntje dat helemaal overgroeid is met bomen.",
  "Het beschilderen van paaseieren (pysanky) is er een eeuwenoude kunst.",
  "De diepste metrohalte ter wereld ligt in Kiev: 105 meter onder de grond.",
  "De borsjtsj — knalrode bietensoep — is het beroemdste gerecht van Oekraïne."],
 woorden:[["pukaty","Oekraïens","scheetjes laten"],
  ["kaka","Oekraïens","poep (kindertaal)"],
  ["metelyk","Oekraïens","vlinder"],
  ["kit","Oekraïens","kat (klinkt als 'kiet')"]],
 fotos:[["Sofiakathedraal","Saint Sophia Cathedral, Kyiv","en"],["Holenklooster van Kiev","Kyiv Pechersk Lavra","en"],["Tunnel van de Liefde","Tunnel of Love (Klevan)","en"],["Kasteel van Kamjanets-Podilsky","Kamianets-Podilskyi Castle","en"],["Lviv","Lviv","nl"]]},
BY:{
 feiten:[
  "In het oerbos van Belarus leven nog wilde wisenten: Europese bizons.",
  "Belarus betekent 'Wit-Rusland'; het land is voor bijna de helft bedekt met bos en moeras.",
  "Het Mirkasteel en het Nesvizj-paleis lijken zo uit een sprookje te komen.",
  "De nationale bibliotheek in Minsk heeft de vorm van een enorme diamant die 's avonds licht geeft.",
  "Belarus heeft zo'n 11.000 meren.",
  "Aardappels zijn er superbelangrijk: er bestaan honderden gerechten mee, zoals draniki (aardappelpannenkoekjes).",
  "Minsk is na de oorlog bijna helemaal opnieuw opgebouwd, met extra brede lanen."],
 woorden:[["puk","Belarussisch","scheetgeluidje: puk!"],
  ["matyljok","Belarussisch","vlindertje"],
  ["kot","Belarussisch","kat"],
  ["bulba","Belarussisch","aardappel (dé nationale trots)"]],
 fotos:[["Mirkasteel","Mir Castle Complex","en"],["Nesvizj-paleis","Nesvizh Castle","en"],["Nationale bibliotheek van Belarus","National Library of Belarus","en"],["Vesting van Brest","Brest Fortress","en"],["Oerbos Belovezjskaja","Belovezhskaya Pushcha","en"]]},
RU:{
 feiten:[
  "Rusland is het grootste land ter wereld: het heeft wel 11 tijdzones.",
  "De Basiliuskathedraal met zijn gekleurde ui-koepels lijkt wel van snoep gemaakt.",
  "Het Bajkalmeer in Rusland is het diepste meer ter wereld: ruim 1600 meter.",
  "De Transsiberische spoorlijn is de langste ter wereld: ruim 9000 km, een week in de trein.",
  "Matroesjka's zijn de beroemde Russische poppetjes-in-poppetjes.",
  "In delen van Siberië wordt het −50 graden — auto's laten ze soms de hele winter aanstaan.",
  "Het Hermitage-museum heeft zoveel kunst dat je jaren nodig hebt om alles te zien — en er wonen katten die muizen vangen!"],
 woorden:[["bjaka","Russisch","iets vies — bah!"],
  ["kaka","Russisch","poep"],
  ["babotsjka","Russisch","vlinder (én vlinderdasje)"],
  ["kot","Russisch","kater"]],
 fotos:[["Basiliuskathedraal","Basiliuskathedraal (Moskou)","nl"],["Rode Plein","Rode Plein","nl"],["Kremlin van Moskou","Kremlin van Moskou","nl"],["Winterpaleis","Winterpaleis","nl"],["Peterhof","Peterhof (paleis)","nl"],["Bolsjojtheater","Bolsjojtheater","nl"]]},
MT:{
 feiten:[
  "Op Malta staan tempels die ouder zijn dan de piramides van Egypte.",
  "Malta is het kleinste EU-land: het past ruim 9 keer in de provincie Utrecht.",
  "Op Malta rijden ze links, net als in Engeland.",
  "De hoofdstad Valletta is een van de kleinste hoofdsteden van Europa — en helemaal werelderfgoed.",
  "Maltees is de enige Semitische taal (familie van het Arabisch) met een Latijns alfabet.",
  "De zee rond Malta is zo helder dat je er meters diep kunt kijken — duikersparadijs!",
  "Films als Gladiator en Troy zijn deels op Malta opgenomen."],
 woorden:[["bużżieqa","Maltees","ballon"],
  ["bassa","Maltees","scheet"],
  ["farfett","Maltees","vlinder"],
  ["qattus","Maltees","kat"]],
 fotos:[["Valletta","Valletta","nl"],["St. John's Co-Cathedral","St John's Co-Cathedral","en"],["Mdina","Mdina","nl"],["Ħaġar Qim","Ħaġar Qim","nl"],["Blauwe Grot","Blue Grotto (Malta)","en"]]},
CY:{
 feiten:[
  "Op Cyprus lopen misschien wel meer katten rond dan mensen.",
  "Volgens de Griekse mythen is de godin Aphrodite geboren uit het schuim van de zee bij Cyprus.",
  "Halloumi, de piepkaas die niet smelt, komt van Cyprus.",
  "Nicosia is de laatste gedeelde hoofdstad ter wereld: er loopt een grens dwars doorheen.",
  "Op Cyprus schijnt de zon zo'n 340 dagen per jaar.",
  "In de bergen van Cyprus kun je 's winters skiën én dezelfde dag zwemmen in zee.",
  "Het oudste parfum ter wereld (4000 jaar oud) is gevonden op Cyprus."],
 woorden:[["papoútsia","Grieks (Cyprus)","schoenen"],
  ["gáta","Grieks","kat"],
  ["sigá sigá","Grieks","rustig aan, langzaamaan"],
  ["kaká","Grieks","poep"]],
 fotos:[["Petra tou Romiou (rots van Aphrodite)","Petra tou Romiou","en"],["Kasteel van Kyrenia","Kyrenia Castle","en"],["Kykkos-klooster","Kykkos Monastery","en"],["Kaap Greco","Cape Greco","en"]]},
TR:{
 feiten:[
  "Istanbul ligt in twee werelddelen tegelijk: Europa én Azië.",
  "In Cappadocië stijgen elke ochtend tientallen luchtballonnen op boven sprookjesachtige rotsen.",
  "De Grote Bazaar in Istanbul heeft meer dan 4000 winkeltjes.",
  "Tulpen komen oorspronkelijk uit Turkije — pas later werden ze Hollands beroemd.",
  "In Pamukkale liggen spierwitte kalkterrassen met warm blauw water.",
  "De Hagia Sophia is bijna 1500 jaar oud en was kerk, moskee én museum.",
  "Turken drinken hun thee (çay) uit kleine tulpvormige glaasjes, de hele dag door."],
 woorden:[["osuruk","Turks","scheet"],
  ["kaka","Turks","poep"],
  ["kelebek","Turks","vlinder"],
  ["kedi","Turks","kat"]],
 fotos:[["Hagia Sophia","Hagia Sophia","nl"],["Sultan Ahmetmoskee (Blauwe Moskee)","Sultan Ahmetmoskee","nl"],["Cappadocië","Cappadocië","nl"],["Pamukkale","Pamukkale","nl"],["Topkapıpaleis","Topkapıpaleis","nl"],["Galatatoren","Galatatoren","nl"]]},
AD:{
 feiten:[
  "De hoofdstad van Andorra ligt het hoogst van alle hoofdsteden van Europa: ruim 1000 meter.",
  "Andorra heeft geen eigen leger, geen vliegveld en geen treinstation.",
  "Inwoners van Andorra worden gemiddeld ouder dan bijna iedereen ter wereld.",
  "Andorra heeft twee staatshoofden tegelijk: de president van Frankrijk en een Spaanse bisschop.",
  "Het hele land is één groot ski- en wandelgebied in de Pyreneeën."],
 woorden:[["pet","Catalaans","scheet — echt, zo schrijf je dat daar!"],
  ["caca","Catalaans","poep"],
  ["papallona","Catalaans","vlinder"]],
 fotos:[["Casa de la Vall","Casa de la Vall","en"],["Andorra la Vella","Andorra la Vella","nl"],["Heiligdom van Meritxell","Our Lady of Meritxell","en"]]},
MC:{
 feiten:[
  "Monaco is zó klein dat het in een groot stadspark past — toch rijdt de Formule 1 er dwars doorheen.",
  "Monaco is het dichtstbevolkte land ter wereld.",
  "Er wonen meer miljonairs per straat dan waar ook in Europa.",
  "Het beroemde circuit loopt gewoon over de straten; de vangrails staan er het hele jaar.",
  "De vorstenfamilie Grimaldi regeert Monaco al meer dan 700 jaar."],
 woorden:[["zut","Frans","verdorie!"],
  ["minou","Frans","poesje"],
  ["youpi","Frans","joepie!"]],
 fotos:[["Casino van Monte Carlo","Monte Carlo Casino","en"],["Prinselijk paleis van Monaco","Prince's Palace of Monaco","en"],["Oceanografisch Museum","Oceanographic Museum of Monaco","en"],["Haven van Monaco","Port Hercules","en"]]},
LI:{
 feiten:[
  "Liechtenstein is wereldkampioen… kunstgebitten maken! De grootste producent van valse tanden.",
  "Het hele land heeft geen vliegveld en maar één ziekenhuis.",
  "De vorst woont écht in het kasteel op de berg boven de hoofdstad Vaduz.",
  "Liechtenstein en Zwitserland delen dezelfde munt: de Zwitserse frank.",
  "Op de nationale feestdag nodigt de vorst het hele volk uit in zijn kasteeltuin."],
 woorden:[["Käsknöpfle","Duits (Liechtenstein)","kaasknoedeltjes"],
  ["Hoi","Liechtensteins","hallo — net als bij ons!"],
  ["Büsi","Alemannisch","poesje"]],
 fotos:[["Kasteel Vaduz","Vaduz Castle","en"],["Kathedraal van Vaduz","Vaduz Cathedral","en"],["Kasteel Gutenberg","Gutenberg Castle","en"]]},
SM:{
 feiten:[
  "San Marino is de oudste republiek ter wereld — al sinds het jaar 301!",
  "Het land ligt boven op een berg, de Monte Titano, met drie torens op de top.",
  "San Marino heeft meer auto's dan inwoners.",
  "Het voetbalelftal van San Marino is een van de zwakste ter wereld — maar elk doelpunt is er een feest.",
  "San Marino ligt helemaal ingesloten door Italië."],
 woorden:[["puzza","Italiaans","stank"],
  ["topolino","Italiaans","muisje"],
  ["farfalla","Italiaans","vlinder"]],
 fotos:[["Guaita","Guaita (tower)","en"],["Monte Titano","Monte Titano","en"],["Palazzo Pubblico","Palazzo Pubblico (San Marino)","en"],["Basiliek van San Marino","Basilica di San Marino","en"]]},
VA:{
 feiten:[
  "Het kleinste land ter wereld: je loopt er in 20 minuten helemaal omheen.",
  "De Zwitserse Garde bewaakt de paus al 500 jaar, in kleurige gestreepte pakken.",
  "De Sint-Pietersbasiliek is de grootste kerk ter wereld.",
  "Michelangelo beschilderde het plafond van de Sixtijnse Kapel — vier jaar lang, vaak liggend op een steiger.",
  "Vaticaanstad heeft een eigen postkantoor, munt én pinautomaat met Latijn erop."],
 woorden:[["crepitus","Latijn","scheet — zelfs in het Latijn!"],
  ["felis","Latijn","kat"],
  ["bombus","Latijn","gebrom (van een hommel)"]],
 fotos:[["Sint-Pietersbasiliek","Sint-Pietersbasiliek","nl"],["Sint-Pietersplein","Sint-Pietersplein","nl"],["Sixtijnse Kapel","Sixtijnse Kapel","nl"],["Zwitserse Garde","Zwitserse Garde","nl"],["Vaticaanse Musea","Vaticaanse Musea","nl"]]}
};
